apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-keda
  labels:
    app: http-server-keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-keda
  template:
    metadata:
      labels:
        app: http-server-keda
    spec:
      containers:
        - name: http-server-keda
          image: quay.io/sgoswami/http-server-keda:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-keda
  labels:
    app: http-server-keda
spec:
  selector:
    app: http-server-keda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: http-server-keda
  labels:
    app: http-server-keda
spec:
  to:
    kind: Service
    name: http-server-keda
  port:
    targetPort: 8080
  tls:
    termination: edge
