apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-server-keda  
spec:
  selector:
    matchLabels:
      app: http-server-keda
  namespaceSelector:
    matchNames:
      - stress # change as per needs          
  endpoints:
    - port: 8080
      path: /metrics      
      interval: 5s
