apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-server-keda  
spec:
  selector:
    matchLabels:
      app: http-server-keda
  namespaceSelector: {}       
  endpoints:
    - scheme: http
      path: /metrics      
      interval: 5s
